name: Clone Repo and push a file

on: 
  push:
    branches: main
  workflow_dispatch:

jobs:
  Clone_GitHub_Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
      - name: Setup Git
        run: |
          git config --global user.email "manthanjgodhasara160901@gmail.com"
          git config --global user.name "manthanjgodhasara"
      # - name: Clone GitHub Repo
      #   run: |          
      #     cd ../../
      #     git clone https://manthanjgodhasara:${{ secrets.ACCESS_TOKEN }}@github.com/manthanjgodhasara/Smile-Face.git
      #     cp ./Clone_Repo_Workflow/Clone_Repo_Workflow/sample.txt ./Smile-Face
      #     cd ./Smile-Face
      #     git checkout -b "new-file-branch"
      #     git add .
      #     git commit -m "Added files"
      #     git push --set-upstream origin new-file-branch
      # - name: Create a PR
      #   run: |
      #     curl -L \
      #     -X POST \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" \
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     https://api.github.com/repos/manthanjgodhasara/Smile-Face/pulls \
      #     -d '{"title":"Adding sample.txt file","body":"Added a file. Please accept","head":"new-file-branch","base":"master"}'
      - name: Loop json file
        run: |
          JSON_CONTENT=$(cat repos.json)
          names=$(echo "$JSON_CONTENT" | jq -r '.[].repo')
          echo "$names"
          IFS=$'\n'
          for repo_name in $names; do

          echo $repo_name
          cd ../../
          git clone https://manthanjgodhasara:${{ secrets.ACCESS_TOKEN }}@github.com/manthanjgodhasara/$repo_name.git
          cp ./Clone_Repo_Workflow/Clone_Repo_Workflow/sample.txt ./$repo_name
          cd ./$repo_name
          git checkout -b "new-file-branch"
          git add .
          git commit -m "Added files"
          git push --set-upstream origin new-file-branch

          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/manthanjgodhasara/$repo_name/pulls \
          -d '{"title":"Adding sample.txt file","body":"Added a file. Please accept","head":"new-file-branch","base":"main"}'
          
          cd ..
          done