name: Clone Repo and push a file

on: 
  push:
    branches: main
  workflow_dispatch:

jobs:
  Clone_GitHub_Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
      - name: Clone GitHub Repo
        run: |
          pwd
          ls
          cd ../../
          pwd
          git clone https://github.com/manthanjgodhasara/Smile-Face.git
          ls
          cp ./Clone_Repo_Workflow/Clone_Repo_Workflow/sample.txt Smile-Face
          cd ./Smile-Face
          ls
          git status
          git checkout -b "new-file-branch"
          git config --global user.email "manthanjgodhasara160901@gmail.com"
          git config --global user.name "Manthan Godhasara"
          git add .
          git status
          git commit -m "Added files"
          git push --set-upstream origin new-file-branch
      # - name: Checkout to another branch
      #   run : 
      # - name: Push files
      #   run: |
          
      #     git status
          