name: Get Last Commit Date from Another Repo

on:
  workflow_dispatch:

jobs:
  get-last-commit-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read repos.json file
        id: set_env
        run: |
          JSON_CONTENT=$(cat repos.json)
          names=$(echo "$JSON_CONTENT" | jq -r '.["ui-repos"][]')
          echo "repos:${names}" >> $REPOS_JSON

      - name: Debug repos.json content
        run: |
          echo "Repos JSON content: $REPOS_JSON"

      - name: Get last commit date from multiple repos
        id: last_commit_dates
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            const reposJson = JSON.parse(`"${{ steps.read_json.outputs.repos }}"`);
            console.log('Parsed JSON:', reposJson);
            const uiRepos = reposJson["ui-repos"];
            console.log(uiRepos);
            const sixMonthsAgo = new Date();
            sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);

            for (const repo of uiRepos) {
              const owner = 'manthanjgodhasara';
              const repoName = repo;

              // Get all branches
              const branches = await github.rest.repos.listBranches({
                owner: owner,
                repo: repoName,
              });

              let latestCommitDate = new Date(0); // Set to epoch start

              // Iterate through each branch and get the latest commit
              for (const branch of branches.data) {
                const commits = await github.rest.repos.listCommits({
                  owner: owner,
                  repo: repoName,
                  sha: branch.name,
                  per_page: 1,
                });
                const commitDate = new Date(commits.data[0].commit.author.date);
                if (commitDate > latestCommitDate) {
                  latestCommitDate = commitDate;
                }
              }

              const lastCommitDate = latestCommitDate.toISOString();

              if (latestCommitDate < sixMonthsAgo) {
                console.log(`Repo: ${repoName} - Last commit date: ${lastCommitDate}`);
              } else {
                console.log(`Repo: ${repoName} - The last commit was made within the last six months.`);
              }
            }

      # - name: Output last commit date
      #   run: echo "The last commit date is:${{ steps.last_commit_date.outputs.last_commit_date }}"
