name: Get Last Commit Date from Another Repo

on:
  workflow_dispatch:

jobs:
  get-last-commit-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get last commit date from another repo
        id: last_commit_date
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            const owner = 'manthanjgodhasara';
            const repo = 'BondAppFrontend';
            const commits = await github.rest.repos.listCommits({
              owner: owner,
              repo: repo,
              per_page: 1,
            });
            const lastCommitDate = commits.data[0].commit.author.date;
            core.setOutput('last_commit_date', lastCommitDate);
            console.log(`Last commit date: ${lastCommitDate}`);

      - name: Output last commit date
        run: echo "The last commit date is:${{ steps.last_commit_date.outputs.last_commit_date }}"
