name: Get Last Commit Date from Another Repo

on:
  workflow_dispatch:

jobs:
  get-last-commit-date:
    runs-on: ubuntu-latest

    steps:
      - name: Get last commit date from another repo
        id: last_commit_date
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            const owner = 'mevijays';
            const repo = 'training-gcp';
            
            // Get all branches
            const branches = await github.rest.repos.listBranches({
              owner: owner,
              repo: repo,
            });
            
            let latestCommitDate = new Date(0); // Set to epoch start

            // Iterate through each branch and get the latest commit
            for (const branch of branches.data) {
              const commits = await github.rest.repos.listCommits({
                owner: owner,
                repo: repo,
                sha: branch.name,
                per_page: 1,
              });
              const commitDate = new Date(commits.data[0].commit.author.date);
              if (commitDate > latestCommitDate) {
                latestCommitDate = commitDate;
              }
            }
            
            const lastCommitDate = latestCommitDate.toISOString();
            core.setOutput('last_commit_date', lastCommitDate);
            console.log(`Last commit date: ${lastCommitDate}`);

      - name: Output last commit date
        run: echo "The last commit date is:${{ steps.last_commit_date.outputs.last_commit_date }}"
