name: Get Last Commit Date

on:
  workflow_dispatch:

jobs:
  get-last-commit-date:
    runs-on: ubuntu-latest

    steps:

    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh -y

    - name: Authenticate with GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: gh auth login --with-token <<< "$ACCESS_TOKEN"

    - name: Get last commit date
      id: last_commit_date
      run: |
        last_commit_date=$(gh api repos/Smile-Face/commits --jq '.[0].commit.author.date')
        echo "Last commit date: $last_commit_date"
    #     echo "::set-output name=last_commit_date::$last_commit_date"

    # - name: Output last commit date
    #   run: echo "The last commit date is: ${{ steps.last_commit_date.outputs.last_commit_date }}"
