name: Get last commit date from repos

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: "ui-repos/api-repos"

jobs:
  get-last-commit-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get last commit date from repos
        id: last_commit_dates
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            const fs = require('fs');
            const path = './repos.json';
            
            const data = fs.readFileSync(path, 'utf8');
            const json = JSON.parse(data);
            
            // Accessing data in the JSON file
            const repos = json["${{github.event.inputs.repo-name}}"]
            console.log('Repos:', repos);

            const sixMonthsAgo = new Date();
            sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);

            for (const repo of ui_repos) {
              const owner = 'manthanjgodhasara';
              const repoName = repo;

              // Get all branches
              const branches = await github.rest.repos.listBranches({
                owner: owner,
                repo: repoName,
              });

              let latestCommitDate = new Date(0); // Set to epoch start

              // Iterate through each branch and get the latest commit
              for (const branch of branches.data) {
                const commits = await github.rest.repos.listCommits({
                  owner: owner,
                  repo: repoName,
                  sha: branch.name,
                  per_page: 1,
                });
                const commitDate = new Date(commits.data[0].commit.author.date);
                if (commitDate > latestCommitDate) {
                  latestCommitDate = commitDate;
                }
              }

              const lastCommitDate = latestCommitDate.toISOString();

              if (latestCommitDate < sixMonthsAgo) {
                console.log(`${repoName} - Last commit date: ${lastCommitDate}`);
              } else {
                console.log(`${repoName} - The last commit was made within the last six months.`);
              }
            }

      # - name: Output last commit date
      #   run: echo "The last commit date is:${{ steps.last_commit_date.outputs.last_commit_date }}"
