name: Veracode Scan

on:
  workflow_dispatch:

jobs:
  fetch-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Workflow Run ID based on name
        id: get_workflow_run
        run: |
          # Fetch workflow runs for the specific workflow
          WORKFLOW_RUNS=$(curl -s -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            "https://api.github.com/repos/manthanjgodhasara/Clone_Repo_Workflow/actions/workflows/get-last-commit-date.yaml/runs")
          echo "Workflow runs: $WORKFLOW_RUNS"
